const passport=require('passport')
const GoogleStrategy=require('passport-google-oauth20').Strategy;
const keys=require('../config/keys');//NO need to say keys.js(i.e extension is not required) sotred in keys since it is returning values;
const mongoose=require('mongoose');
const User=mongoose.model('users'); //2 argument means we are going to load something in mongoose and 1 argument means we are going to fetch somtehing from mongoose
                                    //User object here is our model class

passport.serializeUser((user,done) => {  //take our user model and put some identifying piece of information into it   //serialise user is a predefined function we are going to define our function and pass it to thi serializeuser function
// user here is our instance of user
    done(null,user.id);// this is the identifying piece of information which will identify our user when it log in again
                       //this user.id is not profile id it is the '_id' automatically generated by mongo which is unique
                      //the reason we are using this is because profileid is of google here but user might sign in with facebook or linkedin etc.       
                    //profile id is useful for us just when user is making first attempt to sign in after that we will use mongodb ID 
 });

 passport.deserializeUser((id,done) =>{ //opposite of serializeablity //function to convert user id back our user.
     User.findById(id).then(user=>{
         done(null,user)
     })

 });
 
passport.use(new GoogleStrategy({
    clientID:keys.googleclientID,
    clientSecret:keys.googleclientSecret,
    callbackURL:'http://localhost:5000/auth/google/callback'
},
(accessToken,refreshToken,profile,done) =>{   //This fetch information from google about my account, which will be visible on console
    
    User.findOne({googleId : profile.id})
    .then((existingUser) => {
        if(existingUser)
        {
            //this is for one instance of an user
            // If we already have arecord with this id
            done(null, existingUser);//to tell passport we are all done
        }
        else{
            // if dont have record with this id
            new User({googleId : profile.id}).save() //.save() will save it to our database record, profile.id is the id coming from users profile ,new User wil create new user which is a modelclass
            .then(user => done(null,user));// to know if data is successfully saved 'user' is user who just saved
        }

        
    });
    // console.log('access token',accessToken);  //access token ko he google dekhega aur smjhega ki isko ko maine request grant ki thi photo ya email me changes ki to ye it google can allow this request to access.
    // console.log('refresh token',refreshToken);// we are not using access and refresh token, but access token gets refreshed in small amount of time, so it is related to it.
    // console.log('profile:',profile); // this is what we will be using in our project
}
)
);
